version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
     - "4566:4566"
    environment:
     - SERVICES=s3
     - DEBUG=1
     - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./.localstack:/tmp/localstack"
  lambda:
    build:
      context: ../
      dockerfile: config/Dockerfile
      target: dev
    ports:
      - "9000:8080"
